# Generated by Django 4.0.3 on 2022-04-27 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_remove_board_register_dttm'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='register_dttm',
            field=models.DateTimeField(auto_now=True, verbose_name='등록시간'),
        ),
    ]
