# Generated by Django 4.0.3 on 2022-04-28 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tag', '0001_initial'),
        ('board', '0003_board_register_dttm'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='tags',
            field=models.ManyToManyField(to='tag.tag', verbose_name='테그'),
        ),
    ]
